tendermint/signatory

- .circleci/Dockerfile
- .circleci/config.yml
The Debian one has been something of a Jenga tower, with gcc segfaulting depending on the precise order in which I install clang and certain Rust tooling.
Try CentOS instead, in hopes it will be more reliable.
This also addresses the issues with rustfmt not working as installed in the Docker image.
> .circleci: Use CentOS 7.4-based Docker image

- Cargo.toml
We need to enable target-feature=+aes for aesni to compile with `core::arch`
> Cargo.toml: Various fixups + docs.rs package metadata

- src/ed25519/dalek.rs
- src/ed25519/mod.rs
- src/ed25519/yubihsm.rs
All providers should know the public key which corresponds to their secret key. This is useful for checking the signer is correctly configured.
> Add ed25519::Signer::public_key()

- src/ed25519/public_key.rs
- src/ed25519/verifier.rs
- src/providers/dalek/ed25519.rs
- src/providers/ring/ed25519.rs
- src/providers/sodiumoxide/ed25519.rs
Requires verifiers (which are merely tuple structs) implement all of the same traits as PublicKey derives, since we need them to even though they're only used as PhantomData.
> Add more bounds to the Verifier trait

- Cargo.toml
The nightly backend for ed25519 is selected by "ed25519-dalek/nightly"; the
extra "curve25519-dalek" dependency of signatory doesn't affect it and isn't
needed.
> Remove unnecessary dependency

- .circleci/config.yml
- src/providers/sodiumoxide/ed25519.rs
The Docker image now has libsodium
> .circleci/config.yml: Test sodiumoxide-provider in CI

- Cargo.toml
- src/ed25519/mod.rs
- src/ed25519/public_key.rs
- src/ed25519/signature.rs
- src/ed25519/signer.rs
- src/ed25519/test_macros.rs
- src/lib.rs
- src/macros.rs
- src/providers/dalek/ed25519.rs
- src/providers/ring/ed25519.rs
- src/providers/sodiumoxide/ed25519.rs
- src/providers/yubihsm/ed25519.rs
- src/util.rs
Adds a FromSeed trait that all software implementations of Ed25519 can implement, allowing them to be used interchangably.
Also includes a few miscellaneous code cleanups, including using a macro to generate shared Ed25519 tests.
> Ed25519 FromSeed trait and miscellaneous cleanups

- Cargo.toml
- src/ecdsa/curve/mod.rs
- src/ecdsa/curve/secp256k1/mod.rs
- src/ecdsa/curve/secp256k1/test_vectors.rs
- src/ecdsa/mod.rs
- src/ecdsa/public_key.rs
- src/ecdsa/signer.rs
- src/ecdsa/verifier.rs
- src/ed25519/public_key.rs
- src/ed25519/verifier.rs
- src/lib.rs
- src/providers/dalek/ed25519.rs
- src/providers/ring/ed25519.rs
- src/providers/secp256k1/ecdsa.rs
- src/providers/secp256k1/mod.rs
- src/providers/sodiumoxide/ed25519.rs
Adds a set of traits for verifying ECDSA signatures:
* `ecdsa::verifier::Verifier<C>`: verify SHA-2 message digest
* `ecdsa::verifier::FixedSizedInputVerifier<C>`: verify raw message
Implements these traits for the secp256k1-rs provider
> ECDSA verification support

- .circleci/config.yml
They're set in the `iqlusion/rust-ci` Dockerfile now
> .circleci/config: Remove unnecessary environment variables

- Cargo.toml
- src/ecdsa/curve/mod.rs
- src/ecdsa/signer.rs
- src/ecdsa/verifier.rs
- src/ed25519/signer.rs
- src/ed25519/verifier.rs
They already were. We just didn't mark them as such.
> Mark all Signers and Verifiers as Send safe

- .circleci/config.yml
- benches/ed25519.rs
Benchmarks were not previously covered by CI, and broke due to API changes.
This updates the benchmarks to use the new API, and adds them to CI to ensure they aren't broken by future API changes.
Ideally we'd just ensure the benchmarks compile as opposed to actually running them in CI, but I can't figure out exactly how to do that with criterion.
> Fix benchmarks

- .circleci/config.yml
For CI purposes we only care that the benchmarks compile. We don't actually want to run them because they slow down CI and the results are too variable to be helpful.
> Build but do not run benchmarks in CI

- .circleci/config.yml
- Cargo.toml
This stabilizes support for the yubihsm provider, allowing us to build and test all providers on stable.
> Upgrade yubihsm crate to 0.10.1 (adding stable support)

- .circleci/config.yml
- Cargo.toml
It made sense for Signatory to include the ed25519-dalek provider by default when it was only an Ed25519 library, but now that it also supports ECDSA it doesn't make sense to rope in an Ed25519 dependency by default.
> No default features

- src/ed25519/seed.rs
Supports instantiating an `ed25519::Seed` from a 64-byte keypair string.
Does not presently verify that the public key matches the seed (but it really should!)
> Add ed25519::Seed::from_keypair method

- src/ecdsa/curve/mod.rs
- src/ecdsa/curve/secp256k1/mod.rs
- src/ecdsa/mod.rs
- src/ecdsa/public_key.rs
- src/ecdsa/signature/der.rs
- src/ecdsa/signature/fixed.rs
- src/ecdsa/signature/mod.rs
- src/ecdsa/signer.rs
- src/ecdsa/verifier.rs
- src/ed25519/verifier.rs
- src/error.rs
- src/providers/secp256k1/ecdsa.rs
Splits ECDSA traits up so signers can implement any combination of:
- Signing hashed messages (SHA-256 only) versus raw digests
- Producing ASN.1 DER signatures versus fixed-sized signatures
This removes support for default ECDSA verifiers, but we can add that back with a more sensible API.
> Factor ECDSA traits apart into separate traits per method

- Cargo.toml
- src/ecdsa/curve/mod.rs
- src/ecdsa/curve/nistp256/mod.rs
- src/ecdsa/curve/secp256k1/mod.rs
- src/ed25519/mod.rs
- src/ed25519/public_key.rs
- src/ed25519/verifier.rs
- src/lib.rs
- src/providers/dalek/mod.rs
- src/providers/ring/ecdsa.rs
- src/providers/ring/mod.rs
- src/providers/secp256k1/ecdsa.rs
- src/providers/yubihsm/ecdsa.rs
- src/providers/yubihsm/ed25519.rs
- src/providers/yubihsm/mod.rs
This presently only works with NIST P-256. It's implemented generically, but getting secp256k1 will require some refactoring of the way public keys are handled.
Tested live against a YubiHSM2 and confirmed working, in addition to supporting testing against the MockHSM.
> ECDSA support for yubihsm-provider

- src/asn1.rs
- src/ecdsa/signature/der.rs
- src/ecdsa/signature/fixed.rs
- src/lib.rs
Support for parsing and serializing ECDSA signatures as ASN.1 DER. Signatures are now parsed when loaded via `DERSignature::from_bytes`, and invalid signatures are rejected.
This allows FixedSignature and DERSignature to be converted from one form to another, which will allow unifying the "Fixed" and "DER" ECDSA traits for signers and verifiers (actual work deferred for another PR).
This implementation is heavily inspired by the `br_ecdsa_raw_to_asn1()` and `br_ecdsa_asn1_to_raw()` functions from BearSSL:
https://www.bearssl.org/gitweb/?p=BearSSL;a=blob;f=src/ec/ecdsa_atr.c;h=3a11226e49446667136e5825d9a171649f01aced;hb=8ef7680081c61b486622f2d983c0d3d21e83caad
https://www.bearssl.org/gitweb/?p=BearSSL;a=blob;f=src/ec/ecdsa_rta.c;h=005c62c2dbb84a3aba4ab4e9a2610a8d9257dc02;hb=8ef7680081c61b48 …
> ECDSA DER signature parsing and serialization

- providers/signatory-yubihsm/Cargo.toml
Leverages Signatory's default impls for SHA256Signer and SHA256Verifier.
> signatory-yubihsm: Enable "digest" and "sha2" Signatory features

- providers/signatory-yubihsm/src/lib.rs
Right now they're opaque to rustdoc
> signatory-yubihsm: Make ecdsa and ed25519 modules public

- Cargo.toml
- providers/signatory-ring/Cargo.toml
- providers/signatory-ring/benches/ecdsa.rs
- providers/signatory-ring/src/ecdsa.rs
- providers/signatory-ring/src/ed25519.rs
- src/lib.rs
- src/pkcs8.rs
Allows loading PKCS#8 keys from different providers that support the trait. Presently limited to *ring*.
> Extract 'from_pkcs8' into a trait

- Cargo.toml
We're presently missing docs for the `pkcs8` feature
> Cargo.toml: Build all features on docs.rs

- .circleci/config.yml
- Cargo.toml
- README.md
- providers/signatory-dalek/benches/ed25519.rs
- providers/signatory-ring/benches/ecdsa.rs
- providers/signatory-ring/benches/ed25519.rs
- providers/signatory-ring/src/ecdsa.rs
- providers/signatory-ring/src/ed25519.rs
- providers/signatory-secp256k1/src/lib.rs
- providers/signatory-sodiumoxide/benches/ed25519.rs
- src/ecdsa/public_key.rs
- src/ecdsa/signature/asn1.rs
- src/ecdsa/signature/fixed.rs
- src/ecdsa/signature/pair.rs
- src/ed25519/public_key.rs
- src/ed25519/seed.rs
- src/ed25519/signature.rs
- src/ed25519/test_macros.rs
- src/encoding/asn1.rs
- src/encoding/base64.rs
- src/encoding/decode.rs
- src/encoding/encode.rs
- src/encoding/hex.rs
- src/encoding/macros.rs
- src/encoding/mod.rs
- src/encoding/pkcs8.rs
- src/lib.rs
- src/prelude.rs
- src/signature.rs
- src/test_vector.rs
Factors encoding-related code into a common "encoding" module, and adds the following branchless / data-independent "constant time-ish" encoding implementations:
* `encoding/hex.rs`: Hexadecimal encoding
* `encoding/base64.rs`: Base64 encoding
Both are adapted from these implementations:
https://github.com/Sc00bz/ConstTimeEncoding/
Copyright (c) 2014 Steve "@Sc00bz" Thomas (steve at tobtu dot com)
Licensed under the MIT license (included in comments in each file).
> encoding: Add encoding module with hex and Base64 support

- README.md
- src/encoding/base64.rs
- src/encoding/hex.rs
These are derived from code that was originally licensed as MIT-only, and was therefore explicitly marked as such and called out in the README.md.
The original author @Sc00bz has authorized the derived Rust code to be dual licensed as MIT+Apache 2.0 like the rest of the codebase, so this commit updates the documentation and comments to reflect that.
> Dual license base64.rs and hex.rs as MIT+Apache 2.0

- providers/signatory-ring/src/ecdsa.rs
- providers/signatory-ring/src/lib.rs
Print the fixed signature generated during the test. `cargo test` will only display it in the event the test fails.
This test failed once sporadically, indicating a (not entirely unexpected) bug in the ASN.1 signature serialization code.
Fuzzing the ASN.1 signature serialization code seems like a good idea.
> signatory-ring: Debug info for fixed -> ASN.1 sig test

- providers/signatory-yubihsm/Cargo.toml
- providers/signatory-yubihsm/src/ecdsa.rs
- providers/signatory-yubihsm/src/ed25519.rs
- providers/signatory-yubihsm/src/lib.rs
libsecp256k1 rejects ECDSA signatures which are not in "low S" form.
To maximize compatibility with the cryptocurrency ecosystem, this commit runs all YubiHSM2-generated ECDSA-over-secp256k1 signatures through libsecp256k1 first, explicitly normalizing `s` and then using either a strict DER or fixed serialization.
> signatory-yubihsm: Normalize secp256k1 signatures to "low S" form

- src/encoding/decode.rs
This better matches `encode_to_*`
> encoding: Rename 'decode_*' to 'decode_from_*'

- .circleci/config.yml
rustfmt and clippy are now stable so we no longer need nightly
> .circleci/config.yml: Use Rust 1.29 stable

- .circleci/config.yml
- providers/signatory-yubihsm/src/ecdsa.rs
The `secp256k1` cargo feature was not enabled in CI, and so #83 broke secp256k1 support in the YubiHSM provider.
This fixes secp256k1 support and enables the cargo feature in CI.
> signatory-yubihsm: Fix ECDSA over secp256k1 signing (closes #87)

- providers/signatory-dalek/src/lib.rs
- providers/signatory-secp256k1/src/lib.rs
- providers/signatory-yubihsm/src/ecdsa.rs
- src/curve/mod.rs
- src/ecdsa/digest.rs
- src/ecdsa/mod.rs
- src/ed25519/digest.rs
- src/ed25519/mod.rs
- src/lib.rs
- src/signer/digest.rs
- src/signer/mod.rs
- src/verifier/digest.rs
- src/verifier/mod.rs
Eliminates the need for providers to impl `DigestSigner` and `DigestVerifier` by using generic impls for all Ed25519 and ECDSA signers and verifiers.
> Generic DigestSigner/DigestVerifier impls

- README.md
- providers/signatory-yubihsm/src/ecdsa.rs
Tested live against a YubiHSM2 with *ring* as the verifier (included in the test suite, no MockHSM support)
> yubihsm: NIST P-384 support

- providers/signatory-dalek/benches/ed25519.rs
- providers/signatory-dalek/src/lib.rs
- providers/signatory-ring/benches/ed25519.rs
- providers/signatory-ring/src/ed25519.rs
- providers/signatory-sodiumoxide/benches/ed25519.rs
- providers/signatory-sodiumoxide/src/lib.rs
- src/ed25519/mod.rs
- src/ed25519/seed.rs
- src/ed25519/test_macros.rs
- src/lib.rs
The goal of this trait was to make it a bit easier to initialize signers (i.e. accept a seed byte slice or `ed25519::Seed` via `Into`) but really it's just redundant with `From`, so get rid of it.
> Eliminate ed25519::FromSeed trait

- src/test_vector/mod.rs
- src/test_vector/pkcs8.rs
Gate the whole module, not just the impl of `to_pkcs8()`
> test_vector: Fix PKCS#8 module gating

- src/ed25519/seed.rs
- src/lib.rs
A couple housekeeping items that came up using  Signatory in the KMS.
> Derive Clone on Seed; re-export encoding types

- src/encoding/decode.rs
- src/encoding/encode.rs
Adds a special implementation of `encode_to_file` which configures file modes on Unix platforms, and sets them to `0600` by default.
Also fixes up some previously poor (copypasta) comments on the trait
> encoding: Use 0o600 file mode on Unix; comment improvements

- providers/signatory-yubihsm/src/lib.rs
Allows accessing the same version of the crate as the Signatory provider crate is using
> signatory-yubihsm: Expose the yubihsm crate as a pub extern

- src/curve/mod.rs
- src/curve/nistp256/mod.rs
- src/curve/nistp384/mod.rs
- src/curve/point.rs
- src/curve/secp256k1/mod.rs
- src/ecdsa/public_key.rs
- Describe the encoding as `Elliptic-Curve-Point-to-Octet-String` from section 2.3.3 of SEC 1 (page 10).
- Fix some copy/paste mistakes where `UncompressedPointSize` was documented as not having the `0x04` tag.
> SEC 1 encoding documentation fixups

- Cargo.toml
- providers/signatory-ring/src/ecdsa/p256.rs
- providers/signatory-ring/src/ecdsa/p384.rs
- providers/signatory-ring/src/ed25519.rs
- providers/signatory-secp256k1/benches/ecdsa.rs
- providers/signatory-secp256k1/src/lib.rs
- src/curve/nistp256/mod.rs
- src/curve/nistp384/mod.rs
- src/curve/secp256k1/mod.rs
- src/ecdsa/mod.rs
- src/ecdsa/secret_key.rs
- src/ed25519/seed.rs
- src/encoding/encode.rs
- src/encoding/mod.rs
- src/encoding/pkcs8.rs
- src/lib.rs
Adds an `EcdsaSecretKey` type for representing raw ECDSA secret keys (private `x` scalars) as commonly used in Bitcoin and other cryptocurrencies.
Also adds a `GeneratePkcs8` trait for randomly generating PKCS#8 keypairs.
> ECDSA secret key types and traits

- providers/signatory-dalek/benches/ed25519.rs
- providers/signatory-dalek/src/lib.rs
- providers/signatory-ledger-cosval/src/lib.rs
- providers/signatory-ring/benches/ecdsa.rs
- providers/signatory-ring/benches/ed25519.rs
- providers/signatory-ring/src/ecdsa/p256.rs
- providers/signatory-ring/src/ecdsa/p384.rs
- providers/signatory-ring/src/ecdsa/signer.rs
- providers/signatory-ring/src/ed25519.rs
- providers/signatory-secp256k1/benches/ecdsa.rs
- providers/signatory-sodiumoxide/benches/ed25519.rs
- providers/signatory-sodiumoxide/src/lib.rs
- providers/signatory-yubihsm/src/ecdsa.rs
- providers/signatory-yubihsm/src/ed25519.rs
- src/ecdsa/curve/nistp256/mod.rs
- src/ecdsa/curve/nistp384/mod.rs
- src/ecdsa/curve/secp256k1/mod.rs
- src/ecdsa/mod.rs
- src/ecdsa/public_key.rs
- src/ecdsa/signature/asn1.rs
- src/ecdsa/signature/fixed.rs
- src/ecdsa/signature/mod.rs
- src/ed25519/mod.rs
- src/ed25519/public_key.rs
- src/ed25519/signature.rs
- src/lib.rs
* `Ed25519PublicKey` => `ed25519::PublicKey`
* `Ed25519Signature` => `ed25519::Signature`
* `EcdsaPublicKey` => `ecdsa::PublicKey`
* `EcdsaSignature` => `ecdsa::Signature`
These names were prefixed with the signature type previously to avoid clashes with traits of the same name (i.e. `signatory::PublicKey` and `signatory::Signature`) however the namespace clash can also be avoided by using the `ed25519` and `ecdsa` module names.
This is considered a Rust best practice:
https://github.com/rust-lang/rfcs/pull/356
> Remove redundant "namespacing" from type names

- .circleci/config.yml
- Cargo.toml
- providers/signatory-dalek/Cargo.toml
- providers/signatory-dalek/README.md
- providers/signatory-ledger-cosval/Cargo.toml
- providers/signatory-ledger-cosval/README.md
- providers/signatory-ring/Cargo.toml
- providers/signatory-ring/README.md
- providers/signatory-secp256k1/Cargo.toml
- providers/signatory-secp256k1/README.md
- providers/signatory-sodiumoxide/Cargo.toml
- providers/signatory-sodiumoxide/README.md
- providers/signatory-yubihsm/Cargo.toml
- providers/signatory-yubihsm/README.md
- src/ed25519/mod.rs
- src/lib.rs
- src/signer/mod.rs
- src/verifier/mod.rs
- Adds a basic signing/verification API overview to lib.rs.
- Clarify Apache2 OR MIT dual licensing (i.e. either-or, not both)
> Rustdoc (i.e. API) + licensing doc improvements

- Cargo.toml
Currently failing since the `nightly` feature is enabled:
https://docs.rs/crate/signatory/0.9.0/builds/120117
> Cargo.toml: Fix docs.rs build

- Cargo.toml
- providers/signatory-dalek/src/lib.rs
- src/lib.rs
- src/signer/digest.rs
- src/verifier/digest.rs
- Enable more cargo features (`digest`, `sha2`) on docs.rs
- Link to `docs.rs` for provider crates
- Add link to `signatory-dalek` example
> More documentation fixups

- README.md
Avoid linewrapping acronyms and crate names
> README.md: Use non-breaking hyphens

- src/encoding/encode.rs
Unfortunately we don't have Appveyor set up, so not sure if this is actually fixed.
> Fix unused import on Windows (closes #121)

- src/encoding/pkcs8.rs
Ensure it isn't imported on non-`unix` platforms
> pkcs8: Properly gate FILE_MODE

- Cargo.toml
- providers/signatory-dalek/Cargo.toml
- providers/signatory-dalek/src/lib.rs
- providers/signatory-yubihsm/Cargo.toml
- src/signer/sha2.rs
- src/verifier/sha2.rs
- Upgrades to yubihsm 0.19
- Temporarily disables dalek's DigestSigner/DigestVerifier until it's updated to digest 0.8. See:
https://github.com/dalek-cryptography/curve25519-dalek/pull/201
> Upgrade to digest 0.8

- .circleci/config.yml
- Cargo.toml
- src/error.rs
Fixes critical encode/decode bug in `release` builds
> Upgrade to subtle-encoding v0.3.0

- src/ecdsa/curve/point.rs
This was a copypasta rustc suggestion, however it's also highly redundant as these precise bounds are explicitly specified.
> Simplify trait bounds for Copy impl on ECDSA curve point types

- src/error.rs
fixes missing `TrailingWhitespace` type-case
```
$ cargo build
Updating crates.io index
Compiling proc-macro2 v0.4.27
Compiling unicode-xid v0.1.0
Compiling syn v0.15.29
Compiling failure_derive v0.1.5
Compiling libc v0.2.50
Compiling failure v0.1.5
Compiling zeroize v0.5.2
Compiling rand_core v0.4.0
Compiling rand_os v0.1.3
Compiling quote v0.6.11
Compiling synstructure v0.10.1
Compiling subtle-encoding v0.3.3
Compiling signatory v0.11.2 (/Users/saadtalaat/C1/work/signatory)
error[E0004]: non-exhaustive patterns: `TrailingWhitespace` not covered
--> src/error.rs:187:15
|
187 |         match err {
|               ^^^ pattern `TrailingWhitespace` not covered
error: aborting due to previous error
For more information about this error, try `rustc --explain E0004`.
error: Could not compile …
```
> fix: Missing TrailingWhitespace type-case in subtle-encoding error conversion
